arb-dir: lib/l10n
template-arb-file: app_it.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missing_translations.txt
output-dir: lib/l10n/generated
synthetic-package: false
