name: crypto_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  go_router: ^4.2.8
  intl: ^0.17.0
  mrx_charts: ^0.1.3
  timeago: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cloud_firestore: ^3.4.9
  firebase_auth: ^3.10.0
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
